services:
  - type: web
    name: water-quality-dashboard
    runtime: node
    plan: free
    buildCommand: npm install && npm --prefix server install && npm --prefix client install && npm run build
    startCommand: npm start
    envVars:
      - key: ONENET_PRODUCT_ID
        sync: false
      - key: ONENET_DEVICE_ID
        sync: false
      - key: ONENET_TOKEN
        sync: false
